-- ===== CATEGORY =====
CREATE TABLE Category (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    description VARCHAR2(500)
);

-- ===== PRODUCT =====
CREATE TABLE Product (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(150) NOT NULL,
    description VARCHAR2(1000),
    price NUMBER(10,2) NOT NULL,
    image_url VARCHAR2(255),
    inventory NUMBER, 
    category_id NUMBER,
    
    CONSTRAINT fk_product_category FOREIGN KEY (category_id) REFERENCES Category(id)
);

-- ===== COMBO =====
CREATE TABLE Combo (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(150) NOT NULL,
    description VARCHAR2(1000),
    price NUMBER(10,2) NOT NULL,
    image_url VARCHAR2(255),
    available NUMBER(1) DEFAULT 1
);

-- ===== COMBO ITEM =====
CREATE TABLE ComboItem (
    combo_id NUMBER,
    product_id NUMBER,
    quantity NUMBER DEFAULT 1,
    
    CONSTRAINT fk_combo_item_combo FOREIGN KEY (combo_id) REFERENCES Combo(id),
    CONSTRAINT fk_combo_item_product FOREIGN KEY (product_id) REFERENCES Product(id),
    PRIMARY KEY (combo_id, product_id)
);

-- ===== USER =====
CREATE TABLE "User" (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    username VARCHAR2(50) UNIQUE NOT NULL,
    password_hash VARCHAR2(255) NOT NULL,
    role VARCHAR2(20) CHECK (role IN ('staff', 'admin')),
    active NUMBER(1) DEFAULT 1
);

-- ===== Order Table =====
CREATE TABLE OrderTable (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_number VARCHAR2(10) NOT NULL UNIQUE,
    capacity NUMBER NOT NULL,
    status VARCHAR2(20) DEFAULT 'available' CHECK (status IN ('available', 'taken')),
    location VARCHAR2(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ===== CUSTOMER =====
CREATE TABLE Customer (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    phone VARCHAR2(20),
    email VARCHAR2(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ===== ORDER =====
CREATE TABLE "Order" (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_code VARCHAR2(20) NOT NULL,
    customer_id NUMBER,
    table_id NUMBER,
    total_amount NUMBER(10, 2) DEFAULT 0,
    status VARCHAR2(20) DEFAULT 'pending',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT fk_order_customer FOREIGN KEY (customer_id) REFERENCES Customer(id),
    CONSTRAINT fk_order_table FOREIGN KEY (table_id) REFERENCES OrderTable(id)
);

-- ===== ORDER ITEM =====
CREATE TABLE OrderItem (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id NUMBER NOT NULL,
    product_id NUMBER, 
    combo_id NUMBER,
    quantity NUMBER DEFAULT 1,
    unit_price NUMBER(10,2) NOT NULL,
    
    CONSTRAINT fk_orderitem_order FOREIGN KEY (order_id) REFERENCES "Order"(id),
    CONSTRAINT fk_orderitem_product FOREIGN KEY (product_id) REFERENCES Product(id),
    CONSTRAINT fk_orderitem_combo FOREIGN KEY (combo_id) REFERENCES Combo(id)
    
);
DROP TABLE OrderTable CASCADE CONSTRAINTS;
DROP TABLE ComboItem CASCADE CONSTRAINTS;

DROP TABLE OrderItem CASCADE CONSTRAINTS;
DROP TABLE "Order" CASCADE CONSTRAINTS;
DROP TABLE Combo CASCADE CONSTRAINTS;
DROP TABLE Product CASCADE CONSTRAINTS;
DROP TABLE Category CASCADE CONSTRAINTS;
DROP TABLE "User" CASCADE CONSTRAINTS;
DROP TABLE Customer CASCADE CONSTRAINTS;


